### ISSUE TITLE
Point::isNullOrEmptyString -- trim() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by xpohoc69** [influxdata/influxdb-client-php#80]
Hello! I installed you library. And found such error in my logs.
```
2021-06-23 10:23:39.933384 [109.229.133.164][3961211][][error][php][04215332889720b803140fe794379980][/login/] trim() expects parameter 1 to be string, array given (/srv/builds/www-45061/htdocs/protected/vendor/influxdata/influxdb-client-php/src/InfluxDB2/Point.php:263)
Stack trace:
#0 /srv/builds/www-45061/htdocs/protected/vendor/influxdata/influxdb-client-php/src/InfluxDB2/Point.php(127): InfluxDB2\Point->appendTags()
#1 /srv/builds/www-45061/htdocs/protected/vendor/influxdata/influxdb-client-php/src/InfluxDB2/WritePayloadSerializer.php(31): InfluxDB2\Point->toLineProtocol()
#2 /srv/builds/www-45061/htdocs/protected/vendor/influxdata/influxdb-client-php/src/InfluxDB2/UdpWriter.php(57): generatePayload()
```

I think you need to change condition in this method  ```private function isNullOrEmptyString($str)``` from ```(!isset($str) || trim($str) === '')``` to ```(!is_string($str) || trim($str) === '')```

**Comment by bednar** [comment]
@xpohoc69, thanks for using our client, We will take a look.
